# Generated by Django 5.2.15 on 2026-06-24 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=100)),
                ('ip_address', models.CharField(max_length=20)),
                ('alert_type', models.CharField(max_length=50)),
                ('alert_message', models.TextField()),
                ('device_info', models.TextField(default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='BannedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=20, unique=True)),
                ('reason', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('banned_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(default='', max_length=100)),
                ('ip_address', models.CharField(max_length=20, unique=True)),
                ('mac_address', models.CharField(default='', max_length=20)),
                ('os_info', models.CharField(default='', max_length=200)),
                ('cpu_percent', models.FloatField(default=0)),
                ('ram_percent', models.FloatField(default=0)),
                ('ram_total_gb', models.FloatField(default=0)),
                ('disk_percent', models.FloatField(default=0)),
                ('usb_devices', models.TextField(default='[]')),
                ('usb_count', models.IntegerField(default=0)),
                ('net_sent_mb', models.FloatField(default=0)),
                ('net_recv_mb', models.FloatField(default=0)),
                ('status', models.CharField(default='offline', max_length=20)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SecurityAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=20)),
                ('alert_type', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
