# Generated by Django 5.2.15 on 2026-07-06 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(default='', max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('alert_type', models.CharField(max_length=50)),
                ('alert_message', models.TextField()),
                ('device_info', models.TextField(default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['alert_type'], name='monitor_ale_alert_t_2ced15_idx'), models.Index(fields=['ip_address'], name='monitor_ale_ip_addr_0e5eab_idx'), models.Index(fields=['is_read'], name='monitor_ale_is_read_7f95b0_idx'), models.Index(fields=['timestamp'], name='monitor_ale_timesta_6d99d9_idx')],
            },
        ),
        migrations.CreateModel(
            name='BannedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('reason', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('failed_attempts', models.IntegerField(default=0)),
                ('banned_at', models.DateTimeField(auto_now_add=True)),
                ('unbanned_at', models.DateTimeField(blank=True, null=True)),
                ('auto_unban_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['ip_address'], name='monitor_ban_ip_addr_5c8f88_idx'), models.Index(fields=['is_active'], name='monitor_ban_is_acti_ae14b8_idx'), models.Index(fields=['auto_unban_at'], name='monitor_ban_auto_un_f26e10_idx')],
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(default='', max_length=100)),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('mac_address', models.CharField(default='', max_length=30)),
                ('os_info', models.CharField(default='', max_length=300)),
                ('device_type', models.CharField(default='Unknown', max_length=80)),
                ('agent_version', models.CharField(default='', max_length=30)),
                ('cpu_percent', models.FloatField(default=0)),
                ('ram_percent', models.FloatField(default=0)),
                ('ram_total_gb', models.FloatField(default=0)),
                ('disk_percent', models.FloatField(default=0)),
                ('usb_devices', models.JSONField(blank=True, default=list)),
                ('usb_count', models.IntegerField(default=0)),
                ('net_sent_mb', models.FloatField(default=0)),
                ('net_recv_mb', models.FloatField(default=0)),
                ('open_ports', models.JSONField(blank=True, default=list)),
                ('open_ports_count', models.IntegerField(default=0)),
                ('running_processes', models.JSONField(blank=True, default=list)),
                ('process_count', models.IntegerField(default=0)),
                ('hardware_devices', models.JSONField(blank=True, default=list)),
                ('active_ips', models.JSONField(blank=True, default=list)),
                ('active_ips_count', models.IntegerField(default=0)),
                ('agent_uptime_seconds', models.BigIntegerField(default=0)),
                ('system_boot_time', models.CharField(default='', max_length=100)),
                ('status', models.CharField(default='offline', max_length=20)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('last_offline_at', models.DateTimeField(blank=True, null=True)),
                ('last_online_at', models.DateTimeField(blank=True, null=True)),
                ('total_offline_seconds', models.BigIntegerField(default=0)),
            ],
            options={
                'indexes': [models.Index(fields=['ip_address'], name='monitor_mac_ip_addr_aae459_idx'), models.Index(fields=['status'], name='monitor_mac_status_41722e_idx'), models.Index(fields=['last_seen'], name='monitor_mac_last_se_4d93d9_idx'), models.Index(fields=['device_type'], name='monitor_mac_device__9d1a85_idx')],
            },
        ),
        migrations.CreateModel(
            name='SecurityAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('alert_type', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['ip_address'], name='monitor_sec_ip_addr_805fdf_idx'), models.Index(fields=['alert_type'], name='monitor_sec_alert_t_bab929_idx'), models.Index(fields=['timestamp'], name='monitor_sec_timesta_274c8a_idx')],
            },
        ),
        migrations.CreateModel(
            name='AgentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='online', max_length=20)),
                ('cpu_percent', models.FloatField(default=0)),
                ('ram_percent', models.FloatField(default=0)),
                ('disk_percent', models.FloatField(default=0)),
                ('usb_count', models.IntegerField(default=0)),
                ('open_ports_count', models.IntegerField(default=0)),
                ('process_count', models.IntegerField(default=0)),
                ('active_ips_count', models.IntegerField(default=0)),
                ('net_sent_mb', models.FloatField(default=0)),
                ('net_recv_mb', models.FloatField(default=0)),
                ('agent_uptime_seconds', models.BigIntegerField(default=0)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='monitor.machine')),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['recorded_at'], name='monitor_age_recorde_c27164_idx'), models.Index(fields=['status'], name='monitor_age_status_c601db_idx')],
            },
        ),
    ]
