# Generated by Django 5.2.15 on 2026-07-06 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagedSwitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Main Switch', max_length=100)),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('community', models.CharField(default='public', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('last_polled', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SwitchPort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('if_index', models.IntegerField()),
                ('name', models.CharField(default='', max_length=150)),
                ('status', models.CharField(default='unknown', max_length=20)),
                ('speed_mbps', models.FloatField(default=0)),
                ('connected_macs', models.JSONField(default=list)),
                ('mac_count', models.IntegerField(default=0)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('switch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='monitor.managedswitch')),
            ],
            options={
                'ordering': ['if_index'],
                'unique_together': {('switch', 'if_index')},
            },
        ),
    ]
