# Generated by Django 5.2.15 on 2026-07-06 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_managedswitch_switchport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='switchport',
            options={},
        ),
        migrations.RenameField(
            model_name='switchport',
            old_name='last_seen',
            new_name='last_updated',
        ),
        migrations.AddField(
            model_name='managedswitch',
            name='active_ports',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='managedswitch',
            name='location',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='managedswitch',
            name='status',
            field=models.CharField(default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='managedswitch',
            name='total_ports',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='managedswitch',
            name='community',
            field=models.CharField(default='public', max_length=50),
        ),
        migrations.AlterField(
            model_name='managedswitch',
            name='ip_address',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='managedswitch',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='switchport',
            name='connected_macs',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='switchport',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='switchport',
            name='status',
            field=models.CharField(default='down', max_length=20),
        ),
    ]
