# Generated by Django 5.2.15 on 2026-07-08 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_alter_switchport_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraceHop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hop_number', models.IntegerField()),
                ('ip_address', models.CharField(default='*', max_length=50)),
                ('hostname', models.CharField(default='', max_length=200)),
                ('rtt1_ms', models.FloatField(default=0)),
                ('rtt2_ms', models.FloatField(default=0)),
                ('rtt3_ms', models.FloatField(default=0)),
                ('avg_rtt_ms', models.FloatField(default=0)),
                ('is_timeout', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['hop_number'],
            },
        ),
        migrations.CreateModel(
            name='TraceRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_ip', models.CharField(max_length=20)),
                ('target_name', models.CharField(default='', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('total_hops', models.IntegerField(default=0)),
                ('total_rtt_ms', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.RemoveField(
            model_name='agenthistory',
            name='machine',
        ),
        migrations.RemoveIndex(
            model_name='alert',
            name='monitor_ale_alert_t_2ced15_idx',
        ),
        migrations.RemoveIndex(
            model_name='alert',
            name='monitor_ale_ip_addr_0e5eab_idx',
        ),
        migrations.RemoveIndex(
            model_name='alert',
            name='monitor_ale_is_read_7f95b0_idx',
        ),
        migrations.RemoveIndex(
            model_name='alert',
            name='monitor_ale_timesta_6d99d9_idx',
        ),
        migrations.RemoveIndex(
            model_name='bannedip',
            name='monitor_ban_ip_addr_5c8f88_idx',
        ),
        migrations.RemoveIndex(
            model_name='bannedip',
            name='monitor_ban_is_acti_ae14b8_idx',
        ),
        migrations.RemoveIndex(
            model_name='bannedip',
            name='monitor_ban_auto_un_f26e10_idx',
        ),
        migrations.RemoveIndex(
            model_name='machine',
            name='monitor_mac_ip_addr_aae459_idx',
        ),
        migrations.RemoveIndex(
            model_name='machine',
            name='monitor_mac_status_41722e_idx',
        ),
        migrations.RemoveIndex(
            model_name='machine',
            name='monitor_mac_last_se_4d93d9_idx',
        ),
        migrations.RemoveIndex(
            model_name='machine',
            name='monitor_mac_device__9d1a85_idx',
        ),
        migrations.RemoveIndex(
            model_name='securityalert',
            name='monitor_sec_ip_addr_805fdf_idx',
        ),
        migrations.RemoveIndex(
            model_name='securityalert',
            name='monitor_sec_alert_t_bab929_idx',
        ),
        migrations.RemoveIndex(
            model_name='securityalert',
            name='monitor_sec_timesta_274c8a_idx',
        ),
        migrations.RenameField(
            model_name='machine',
            old_name='active_ips_count',
            new_name='running_apps_count',
        ),
        migrations.RemoveField(
            model_name='bannedip',
            name='auto_unban_at',
        ),
        migrations.RemoveField(
            model_name='bannedip',
            name='failed_attempts',
        ),
        migrations.RemoveField(
            model_name='bannedip',
            name='unbanned_at',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='active_ips',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='agent_uptime_seconds',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='hardware_devices',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='last_offline_at',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='last_online_at',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='process_count',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='running_processes',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='system_boot_time',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='total_offline_seconds',
        ),
        migrations.AddField(
            model_name='machine',
            name='hardware_info',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='machine',
            name='running_apps',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='machine',
            name='uptime_seconds',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='machine',
            name='windows_version',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='alert',
            name='hostname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='alert',
            name='ip_address',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='bannedip',
            name='ip_address',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='agent_version',
            field=models.CharField(default='2.0', max_length=20),
        ),
        migrations.AlterField(
            model_name='machine',
            name='device_type',
            field=models.CharField(default='PC', max_length=50),
        ),
        migrations.AlterField(
            model_name='machine',
            name='ip_address',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='mac_address',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='machine',
            name='open_ports',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='os_info',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='machine',
            name='usb_devices',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='securityalert',
            name='ip_address',
            field=models.CharField(max_length=20),
        ),
        migrations.AddField(
            model_name='tracehop',
            name='traceroute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hops', to='monitor.traceroute'),
        ),
        migrations.DeleteModel(
            name='AgentHistory',
        ),
    ]
