# Generated by Django 6.0.7 on 2026-07-15 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_tracehop_traceroute_remove_agenthistory_machine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannedip',
            name='auto_unban_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bannedip',
            name='failed_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bannedip',
            name='unbanned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
